### ISSUE TITLE
Open new tab without focusing on it

### ISSUE THREAD

**Issue by evandrocoan** [michurin/chrome-extension-bookmarks-on-new-tab#1]
I usually open several pages at once, but when I `Shift+Click` to open the bookmark on a new tab, it switch my tab to it, making it harder to open the next link, as I have to switch back to the `Ultra light newtab page with bookmarks` before opening the next bookmark.

May be another shortcut as `Ctrl+Click` could be added to open it in a new tab without switching focus to the new tab just opened?

**Comment by michurin** [comment]
Great idea! I'll do it for the next coulple of weeks.

**Comment by michurin** [comment]
It turned out easier than I expected. New version 0.5.2.0 has already published on WebStore. Try to restart your brouser to force extensions update. `Ctrl-Click` works as you said. Have you enjoyed? ,-) @evandrocoan

**Comment by michurin** [comment]
BTW, if you are a happy MacBook owner, I have bad news for you. `Ctrl-Click` doesn't work on MacBooks. I know how to fix it and I'll do it. But not today )

**Comment by evandrocoan** [comment]
Thanks! It is working now. I use Window 10.
