### ISSUE TITLE
Зачем этому расширению чтение и изменение всех ваших данных на веб-сайтах, которые вы посещаете?

### ISSUE THREAD

**Issue by f242** [michurin/chrome-extension-bookmarks-on-new-tab#2]
Собственно вопрос зачем этому расширению чтение и изменение всех ваших данных на веб-сайтах, которые вы посещаете?

**Comment by michurin** [comment]
Точно не помню, но скорее всего, чтобы иметь доступ к иконкам сайтов. Вы можете взять исходники и [поиграться с правами тут](https://github.com/michurin/chrome-extension-bookmarks-on-new-tab/blob/master/bookmarks-on-new-tab/manifest.json#L44). Гугл постоянно совершенствует политики, возможно, сейчас уже есть возможности обойтись более точечными правами. Я чекну на досуге, но пулреквесты приму с благодарностью.

**Comment by f242** [comment]
Спасибо
